name: CVE-2023-25168
main: moe.orangemc.cve_2023_25168.CVE_2023_25168
version: 0.0.1
api: "1.19"
authors:
  - Astro_angelfish
  - ShiinaSekiu
  - T4x0r
description: An exploitation code for CVE-2023-25168

